package sv.com.model;
// Generated 11-ene-2017 9:17:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private Integer idCategoria;
	private String descripcion;
	private Date fechaRegistro;
	private Date fechaActualizacion;
	private Set<Tips> tipses = new HashSet<Tips>(0);
	private Set<Receta> recetas = new HashSet<Receta>(0);

	public Categoria() {
	}

	public Categoria(String descripcion, Date fechaRegistro) {
		this.descripcion = descripcion;
		this.fechaRegistro = fechaRegistro;
	}

	public Categoria(String descripcion, Date fechaRegistro, Date fechaActualizacion, Set<Tips> tipses,
			Set<Receta> recetas) {
		this.descripcion = descripcion;
		this.fechaRegistro = fechaRegistro;
		this.fechaActualizacion = fechaActualizacion;
		this.tipses = tipses;
		this.recetas = recetas;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Set<Tips> getTipses() {
		return this.tipses;
	}

	public void setTipses(Set<Tips> tipses) {
		this.tipses = tipses;
	}

	public Set<Receta> getRecetas() {
		return this.recetas;
	}

	public void setRecetas(Set<Receta> recetas) {
		this.recetas = recetas;
	}

}
