package sv.com.model;
// Generated 11-ene-2017 9:17:44 by Hibernate Tools 4.3.1.Final

/**
 * ContactoId generated by hbm2java
 */
public class ContactoId implements java.io.Serializable {

	private int idContacto;
	private int idUsuario;

	public ContactoId() {
	}

	public ContactoId(int idContacto, int idUsuario) {
		this.idContacto = idContacto;
		this.idUsuario = idUsuario;
	}

	public int getIdContacto() {
		return this.idContacto;
	}

	public void setIdContacto(int idContacto) {
		this.idContacto = idContacto;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactoId))
			return false;
		ContactoId castOther = (ContactoId) other;

		return (this.getIdContacto() == castOther.getIdContacto()) && (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdContacto();
		result = 37 * result + this.getIdUsuario();
		return result;
	}

}
