package sv.com.model;
// Generated 11-ene-2017 9:17:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Contacto generated by hbm2java
 */
public class Contacto implements java.io.Serializable {

	private ContactoId id;
	private Usuario usuario;
	private String asunto;
	private String mensaje;
	private Date fechaRegistro;
	private Date fechaActualizacion;

	public Contacto() {
	}

	public Contacto(ContactoId id, Usuario usuario, String asunto, String mensaje) {
		this.id = id;
		this.usuario = usuario;
		this.asunto = asunto;
		this.mensaje = mensaje;
	}

	public Contacto(ContactoId id, Usuario usuario, String asunto, String mensaje, Date fechaRegistro,
			Date fechaActualizacion) {
		this.id = id;
		this.usuario = usuario;
		this.asunto = asunto;
		this.mensaje = mensaje;
		this.fechaRegistro = fechaRegistro;
		this.fechaActualizacion = fechaActualizacion;
	}

	public ContactoId getId() {
		return this.id;
	}

	public void setId(ContactoId id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

}
