package sv.com.model;
// Generated 11-ene-2017 9:17:44 by Hibernate Tools 4.3.1.Final

/**
 * RecetaFavoritaId generated by hbm2java
 */
public class RecetaFavoritaId implements java.io.Serializable {

	private int idRecetaFavorita;
	private int idReceta;
	private int idCategoria;
	private int idUsuario;
	private int idTipoComida;

	public RecetaFavoritaId() {
	}

	public RecetaFavoritaId(int idRecetaFavorita, int idReceta, int idCategoria, int idUsuario, int idTipoComida) {
		this.idRecetaFavorita = idRecetaFavorita;
		this.idReceta = idReceta;
		this.idCategoria = idCategoria;
		this.idUsuario = idUsuario;
		this.idTipoComida = idTipoComida;
	}

	public int getIdRecetaFavorita() {
		return this.idRecetaFavorita;
	}

	public void setIdRecetaFavorita(int idRecetaFavorita) {
		this.idRecetaFavorita = idRecetaFavorita;
	}

	public int getIdReceta() {
		return this.idReceta;
	}

	public void setIdReceta(int idReceta) {
		this.idReceta = idReceta;
	}

	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdTipoComida() {
		return this.idTipoComida;
	}

	public void setIdTipoComida(int idTipoComida) {
		this.idTipoComida = idTipoComida;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecetaFavoritaId))
			return false;
		RecetaFavoritaId castOther = (RecetaFavoritaId) other;

		return (this.getIdRecetaFavorita() == castOther.getIdRecetaFavorita())
				&& (this.getIdReceta() == castOther.getIdReceta())
				&& (this.getIdCategoria() == castOther.getIdCategoria())
				&& (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getIdTipoComida() == castOther.getIdTipoComida());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRecetaFavorita();
		result = 37 * result + this.getIdReceta();
		result = 37 * result + this.getIdCategoria();
		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdTipoComida();
		return result;
	}

}
