package sv.com.model;
// Generated 11-ene-2017 9:17:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * RecetaFavorita generated by hbm2java
 */
public class RecetaFavorita implements java.io.Serializable {

	private RecetaFavoritaId id;
	private Receta receta;
	private Date fechaRegistro;
	private Date fechaActualizacion;

	public RecetaFavorita() {
	}

	public RecetaFavorita(RecetaFavoritaId id, Receta receta, Date fechaRegistro) {
		this.id = id;
		this.receta = receta;
		this.fechaRegistro = fechaRegistro;
	}

	public RecetaFavorita(RecetaFavoritaId id, Receta receta, Date fechaRegistro, Date fechaActualizacion) {
		this.id = id;
		this.receta = receta;
		this.fechaRegistro = fechaRegistro;
		this.fechaActualizacion = fechaActualizacion;
	}

	public RecetaFavoritaId getId() {
		return this.id;
	}

	public void setId(RecetaFavoritaId id) {
		this.id = id;
	}

	public Receta getReceta() {
		return this.receta;
	}

	public void setReceta(Receta receta) {
		this.receta = receta;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

}
