package sv.com.model;
// Generated 11-ene-2017 9:17:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoComida generated by hbm2java
 */
public class TipoComida implements java.io.Serializable {

	private Integer idTipoComida;
	private String descripcion;
	private Date fechaRegistro;
	private Date fechaActualizacion;
	private Set<Receta> recetas = new HashSet<Receta>(0);

	public TipoComida() {
	}

	public TipoComida(String descripcion, Date fechaRegistro) {
		this.descripcion = descripcion;
		this.fechaRegistro = fechaRegistro;
	}

	public TipoComida(String descripcion, Date fechaRegistro, Date fechaActualizacion, Set<Receta> recetas) {
		this.descripcion = descripcion;
		this.fechaRegistro = fechaRegistro;
		this.fechaActualizacion = fechaActualizacion;
		this.recetas = recetas;
	}

	public Integer getIdTipoComida() {
		return this.idTipoComida;
	}

	public void setIdTipoComida(Integer idTipoComida) {
		this.idTipoComida = idTipoComida;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Set<Receta> getRecetas() {
		return this.recetas;
	}

	public void setRecetas(Set<Receta> recetas) {
		this.recetas = recetas;
	}

}
