package sv.com.model;
// Generated 11-ene-2017 9:17:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoMedida generated by hbm2java
 */
public class TipoMedida implements java.io.Serializable {

	private Integer idTipoMedida;
	private String descripcion;
	private Date fechaRegistro;
	private Date fechaActualizacion;
	private Set<IngredienteReceta> ingredienteRecetas = new HashSet<IngredienteReceta>(0);

	public TipoMedida() {
	}

	public TipoMedida(String descripcion, Date fechaRegistro) {
		this.descripcion = descripcion;
		this.fechaRegistro = fechaRegistro;
	}

	public TipoMedida(String descripcion, Date fechaRegistro, Date fechaActualizacion,
			Set<IngredienteReceta> ingredienteRecetas) {
		this.descripcion = descripcion;
		this.fechaRegistro = fechaRegistro;
		this.fechaActualizacion = fechaActualizacion;
		this.ingredienteRecetas = ingredienteRecetas;
	}

	public Integer getIdTipoMedida() {
		return this.idTipoMedida;
	}

	public void setIdTipoMedida(Integer idTipoMedida) {
		this.idTipoMedida = idTipoMedida;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Set<IngredienteReceta> getIngredienteRecetas() {
		return this.ingredienteRecetas;
	}

	public void setIngredienteRecetas(Set<IngredienteReceta> ingredienteRecetas) {
		this.ingredienteRecetas = ingredienteRecetas;
	}

}
