package sv.com.model;
// Generated 11-ene-2017 9:17:44 by Hibernate Tools 4.3.1.Final

/**
 * TipsId generated by hbm2java
 */
public class TipsId implements java.io.Serializable {

	private int idTips;
	private int idUsuario;
	private int idCategoria;

	public TipsId() {
	}

	public TipsId(int idTips, int idUsuario, int idCategoria) {
		this.idTips = idTips;
		this.idUsuario = idUsuario;
		this.idCategoria = idCategoria;
	}

	public int getIdTips() {
		return this.idTips;
	}

	public void setIdTips(int idTips) {
		this.idTips = idTips;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipsId))
			return false;
		TipsId castOther = (TipsId) other;

		return (this.getIdTips() == castOther.getIdTips()) && (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getIdCategoria() == castOther.getIdCategoria());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTips();
		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdCategoria();
		return result;
	}

}
