package sv.com.model;
// Generated 11-ene-2017 9:17:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Tips generated by hbm2java
 */
public class Tips implements java.io.Serializable {

	private TipsId id;
	private Categoria categoria;
	private Usuario usuario;
	private String descripcion;
	private String imagen;
	private int publico;
	private Date fechaRegistro;
	private Date fechaActualizacion;

	public Tips() {
	}

	public Tips(TipsId id, Categoria categoria, Usuario usuario, String descripcion, String imagen, int publico,
			Date fechaRegistro) {
		this.id = id;
		this.categoria = categoria;
		this.usuario = usuario;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.publico = publico;
		this.fechaRegistro = fechaRegistro;
	}

	public Tips(TipsId id, Categoria categoria, Usuario usuario, String descripcion, String imagen, int publico,
			Date fechaRegistro, Date fechaActualizacion) {
		this.id = id;
		this.categoria = categoria;
		this.usuario = usuario;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.publico = publico;
		this.fechaRegistro = fechaRegistro;
		this.fechaActualizacion = fechaActualizacion;
	}

	public TipsId getId() {
		return this.id;
	}

	public void setId(TipsId id) {
		this.id = id;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public int getPublico() {
		return this.publico;
	}

	public void setPublico(int publico) {
		this.publico = publico;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

}
